### PR TITLE
35 style favorites page content am

### LINKED ISSUE #35: style favorites page content

### PR DESCRIPTION
**Pull request by Autumn-Martin**
## Type of change:
- [x] New feature
- [] Bug fix
- [] Testing
- [] Update

### New feature
This styles the view for the favorites page!

## Necessary checkmarks:
- [X] Code runs locally
- [] All tests pass

Current display: 
screen shot 2018-12-12 at 2 36 17 pm

screen shot 2018-12-12 at 2 35 02 pm

### CODE REVIEW

**Comment by Autumn-Martin** [comment]
@ameseee What do you think? Any suggestions? Any ideas on how to avoid the overlap of the buttons over the table? I've tried adding margins in different spots, and am not getting any promising results.

**Comment by ameseee** [comment]
Hi @Autumn-Martin and @abdullaqudrat - this is looking so great!

As far as the overlap, I'd probably limit the size of the container, then add some overflow/scroll so if the number of items on the table go longer, the user has to scroll to view them. Here is a resource that may be helpful - https://css-tricks.com/almanac/properties/o/overflow/

One question I have is in the "add to playlist" column, does each row have two buttons, or are there two icons on the one button?

**Comment by Autumn-Martin** [comment]
Thanks @ameseee! That looks like a great resource. Each row has two icons on one button, but I can see how that could be confusing. I can change it to a single symbol to avoid this--just a 'plus' sign would probably make sense.

**Comment by Autumn-Martin** [comment]
screen shot 2018-12-12 at 5 27 57 pm

**Pull request merged**
